sudo: required 

language: python
python:
  - "3.6.4"
# command to run tests
# install:
#   - pip install -r requirements.txt
# script: nosetests -v

services: 
    - docker
before_install: 
    - docker build -t easycrm .


deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY1"
  region: "us-east-1"  
  app: "sample-docker-react"
  env: "Sampledockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-092354816535"
  bucket_path: "EBApptest" 
  on:
    branch: master
  skip_cleanup: true
