sudo: required 

language: python
python:
  - "3.6.4"
services: 
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY1"
  region: "us-east-1"  
  app: "sample-docker-react"
  env: "Sampledockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-092354816535"
  bucket_path: "EBApptest" 
  on:
    branch: master
  skip_cleanup: true
